development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: codequest_tea_app_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: codequest_tea_app_test
  pool: 5
  username: postgres
  password: postgres